### ISSUE TITLE
outputsize='full' in get_daily_adjusted() traceback

### ISSUE THREAD

**Issue by SteffenNa** [RomelTorres/alpha_vantage#10]
Hello, when i use the optional argument outputsize='full' in the get_daily_adjusted() function i get:
TypeError: __init__() got an unexpected keyword argument 'outputsize'

code snipped I use:
```
import alpha_vantage
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='my API key', outputsize='full')
data = ts.get_daily_adjusted('VOO')
```
what am I doing wrong?
another question: Is there a way to retrieve a defined timeframe of data (like for example the last year)?

**Comment by RomelTorres** [comment]
Hi there Steffen, 

The problem is that the outputsize parameter hast to be used in the api call, not in the class initialization.
```
import alpha_vantage
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='YOUR_API_KEY')
data = ts.get_daily_adjusted('VOO', outputsize='full')
```

with regard to your second question, I would suggest using the **pandas** format supported by the module, pandas is quite popular in python and finance and allows you to slice your data nicely.

Best Regards 

Romel Torres
