### ISSUE TITLE
List of possible symbols

### ISSUE THREAD

**Issue by ctwhome** [RomelTorres/alpha_vantage#11]
How is possible to get a list of accessible symbols?

**Comment by RomelTorres** [comment]
That is a feature that should be requested to the [alphavantage](https://www.alphavantage.co/support/#support) people. Usually you can contact them and they reply rather fast. If they implement the call I will update the python library to support the call. Does this answer your question?

Best Regards 
Romel

**Comment by ctwhome** [comment]
Hi Romel, 
it does, thank s for answering! 
I have already asked them, time ago, but not answer. I couldn't find either a list of symbols supported. I hoped you could have some info about it!

btw, congrats for the library and thanks for sharing!
best
Jesus

**Comment by RomelTorres** [comment]
Ah, well... if they reply to you and give you an idea on how to do that (instead of offering an API call) I could help implementing in it in python.
For the time being I will close the issue, if you get more info, do reopen the issue and we'll see where we go from there. 

Thanks for posting and using the library...

All the best,

Romel
