### ISSUE TITLE
Function DIGITAL_CURRENCY_INTRADAY was not found in API doc?

### ISSUE THREAD

**Issue by van0303** [RomelTorres/alpha_vantage#121]
Function DIGITAL_CURRENCY_INTRADAY was not found in API doc?
How could we get it?

**Comment by amenzel1986** [comment]
I tried to replicate the code found in the readme and could not get `data, meta_data = cc.get_digital_currency_intraday(symbol='BTC', market='CNY')` to run. This makes sense because according to [Alpha Vantage themselves](https://www.alphavantage.co/documentation/ )no intraday information for Forex or cryptocurrencies is available. Perhaps the above code could be replaced with: `data, meta_data = cc.get_digital_currency_daily(symbol='BTC', market='CNY')` to reduce confusion.

**Comment by PatrickAlphaVantage** [comment]
This has been removed from develop - you're right, it is no crypto intraday longer supported.

Thanks!

**Comment by shjoshi95** [comment]
> This has been removed from develop - you're right, crypto intraday is no longer supported.
> 
> Thanks!

Out of curiosity, do you know why the crypto intraday call is no longer supported? Seems like a good use case that would bring the crypto APIs in parity with the equities APIs.
