### ISSUE TITLE
Please add the "Quote Endpoint" function

### ISSUE THREAD

**Issue by marvin-hansen** [RomelTorres/alpha_vantage#123]
- [ ] Please add the "Quote Endpoint" function

https://www.alphavantage.co/documentation/#latestprice

#A lightweight alternative to the time series APIs, this service returns the latest price and volume information for a security of your choice.#

**Comment by JeremyFlorence** [comment]
It looks like it's been added to timeseries.py, but the update hasn't been released to pypi yet. I would also like to use this in my project.

**Comment by RomelTorres** [comment]
Hi there, if you need it. Just install the component from github. In the readme of the repo says how to do it. I haven't released the library in pipy because I changed OS and lost my keys to pipy I just have to get around recovering those credentials.

**Comment by neel-one** [comment]
Hi,
I installed the updates from github, but I get this error

ValueError: failed to cast to 'float64' (Exception was: could not convert string to float: 'NVDA'), with the full error being outlined in a previous post (I got the same error) https://github.com/RomelTorres/alpha_vantage/issues/90

I know you mentioned you are busy, so all I wonder is if this is a known issue and what I can do to try to fix it or if it is already fixed.

**Comment by PatrickAlphaVantage** [comment]
@neel-one @marvin-hansen @RomelTorres 
I'm new to the team at alpha vantage, and this has been bugging me too haha. Great issue raise.
So every other dictionary that alpha vantage returns has floats for values. The quote endpoint also returns a string in the "symbol" section. 

> https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=MSFT&apikey=demo

Which is throwing off the function that calls the API

I have the change fixed in develop (and with some testing can fix to master):
https://github.com/RomelTorres/alpha_vantage/pull/145

If you run:
`pip install git+https://github.com/RomelTorres/alpha_vantage.git@develop`
You can get the updated code where stock quotes now work properly

Here is a sample:
```
from alpha_vantage.timeseries import TimeSeries
# Your key here
key = <key>
ts = TimeSeries(key, output_format='pandas')
quotes, meta_data = ts.get_quote_endpoint('AAPL')
quotes
```

Thanks!
