### ISSUE TITLE
Still not getting correct amount of data

### ISSUE THREAD

**Issue by CalumTowler** [RomelTorres/alpha_vantage#179]
I saw that you closed issue #150 which was apparently what my issue #170 was a duplicate of, however  I'm still getting variable number of datapoints for the intraday stock call. As an example, calling the MSFT stock is giving me 1934 and 1945 datapoints each time I call it. There should be 1950 datapoints each time but the real problem for what I want to use it for is that the numbers vary both within a stock and between stocks. This makes things like correlation inaccurate and simply not work. If you need more details I can provide them but they're the same as in #170.

Thanks.

**Comment by PatrickAlphaVantage** [comment]
Ah thanks for the follow up. I didn't test on the rest of the samples you gave:
`import alpha_vantage
import os
import pandas

from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries()
data, _ = ts.get_intraday(interval='1min', symbol='MSFT', outputsize='full')
print(len(data))
data2, _ = ts.get_intraday(interval='1min', symbol='TSLA', outputsize='full')
print(len(data2))
data3, _ = ts.get_intraday(interval='1min', symbol='MU', outputsize='full')
print(len(data3))
data4, _ = ts.get_intraday(interval='1min', symbol='FB', outputsize='full')
print(len(data4))

print(data.keys())
# missing days

print(set(data.keys()).difference(data2.keys()))`

We fixed the issue with the specified ticker in that issue. I'll keep the issue here open. At the moment, a suggested workaround would be to remove all timestamps that are not in all datasets you are comparing, using the difference() function from the set object. 

How many tickers are you looking to do a intraday 1minute interval correlation on?

**Comment by CalumTowler** [comment]
Eventually up to 30 so will need consistent numbers of datapoints across them all. 

In regards to your solution, this will work for writing/testing but for actual use this wouldn't be good enough. Do you think this a fixable issue at some point?

**Comment by PatrickAlphaVantage** [comment]
100% a fixable issue, but we don't have a time frame on when yet.

**Comment by CalumTowler** [comment]
Awesome, thanks for the temporary workaround.

**Comment by PatrickAlphaVantage** [comment]
So this may be TMI, but another workaround you could do till this is fixed is constantly save the 30 ticker quotes to your own mongoDB. MongoDB is lightweight so you don't have to really maintain it like a postgres

You could run something like this:

```
from arctic import Arctic
from alpha_vantage.timeseries import TimeSeries
import os

# Connect to Local MONGODB
store = Arctic('localhost')

# Create the library - defaults to VersionStore
store.initialize_library('HISTORICAL_DATA')

# Access the library
library = store['HISTORICAL_DATA']

key = os.path.expandvars("$ALPHA_VANTAGE_HIGHER_KEY")
ts = TimeSeries(key, output_format='pandas')

aapl_data, meta_data = ts.get_daily(symbol='AAPL', outputsize='full')
meta_data_aapl = {'Source' : "Alpha Vantage"}


# Store the data in the library
library.write('AAPL', aapl_data, metadata=meta_data_aapl)

# # Reading the data
item = library.read('AAPL')
aapl = item.data
metadata = item.metadata

aapl_data, meta_data = ts.get_daily(symbol='AAPL')
```

And then in later files, access it with:
```
from arctic import Arctic
import os

store = Arctic('localhost')
library = store['HISTORICAL_DATA']
item = library.read('AAPL')
item.data.tail(3)
```

**Comment by CalumTowler** [comment]
Okay cool, I'll have a play with this. Thanks a lot!
