### ISSUE TITLE
Make pandas dependency optional

### ISSUE THREAD

**Issue by rkhwaja** [RomelTorres/alpha_vantage#34]
It causes a lot of dependencies, including pycrypto which is difficult to install since it includes native libraries.
Maybe we can import it on demand?

**Comment by rerobins** [comment]
Another thought would be to split this into two projects.  One that just provides your alpha vantage access and one that provides the analysis that is using pandas.

**Comment by RomelTorres** [comment]
Hi @rkhwaja and @rerobins. I already have a version in my local repository where you can do ```pip install alpha_vantage``` and it will install the library without pandas support and if you do ```pip install alpha_vantage[pandas]``` it will install the library with pandas support. I haven't had enough free time to test everything, since I am also reworking the unittests to mock the url calls and it takes some time. Bear with me ;) 

Saludos Romel

**Comment by RomelTorres** [comment]
Hi @rkhwaja and @rkhwaja, I committed last night the changes needed in the codebase for addressing this issue. I hope that over the weekend I can roll out the update to PiPy. 

Saludos Romel

**Comment by rkhwaja** [comment]
Works great - thanks
