### ISSUE TITLE
Missing values on x-axis 

### ISSUE THREAD

**Issue by martindebruin** [RomelTorres/alpha_vantage#73]
Hi

I love this python wrapper! It's great!

I'm trying to get some charts going and I have some problems getting the dates on the X-axis to show up when pulling technical indicators.

![image](https://user-images.githubusercontent.com/652761/40424371-a9cb1bdc-5e95-11e8-9178-2d3760f87189.png)

I'm pasting my code below

`function="rsi"
symbol="msft"
interval="daily"
time_period="60"
series_type="close"
apikey="MYAPIKEY"

data = { "function": function,
         "interval" : interval,
         "time_period" : time_period,
         "series_type" : series_type,
         "symbol": symbol, 
         "apikey": apikey } 

ts = TimeSeries(key=apikey)

data, meta_data = ts.get_intraday(symbol)

ti = TechIndicators(key=apikey, output_format='pandas')
data, meta_data = ti.get_rsi(symbol=symbol, interval=interval, time_period=time_period)

data.plot()
plt.title(meta_data.get("2: Indicator","none"))
plt.grid()
plt.tight_layout()

filename = meta_data.get("1: Symbol", "none")+".png"

plt.savefig(filename)`

I've tried running your examples unedited but still no dates - is it me?

Cheers and thanks again for this wonderful wrapper

**Comment by thim0o** [comment]
I have this issue as well!

**Comment by abhijeet-pandey** [comment]
I have this issue as well!

**Comment by user-names** [comment]
I also have this issue.

**Comment by czbo** [comment]
Looks like when pandas reads the data into the DataFrame when using from_dict(), it doesn't parse the date string into its datetime64 type for the index. you can add this line after you get the pandas object to convert the index into proper datetime64 format, and then plotting it will show the x-axis with dates:

data.index = pd.to_datetime(data.index)

Perhaps you can consider using pandas.read_json(json) to process the json string, instead of DataFrame.from_dict(), because read_json() will attempt to parse the axis to date type.
